name: Fon Takip Güncelleme

permissions:
  contents: write

on:
  schedule:
    - cron: "0 22 * * *"

  workflow_dispatch:


jobs:

  update-data:

    runs-on: ubuntu-latest

    steps:

      - name: Kodları indir
        uses: actions/checkout@v5
        with:
          fetch-depth: 0


      - name: Python kurulumu
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"


      - name: Güncelleme scriptini çalıştır
        run: |
          python update.py


      - name: Değişiklikleri kaydet
        run: |

          git config user.name "FonTakip Bot"

          git config user.email "actions@github.com"

          git add data.json

          git diff --cached --quiet || git commit -m "Otomatik fon güncellemesi"


      - name: GitHub'a gönder
        run: |

          git push
